src/main/resources/liricalHTML.ftl

They were previously not under the header "Excluded Phenotypic Features" where they belong.
Also fixed erroneous `<section>` tag which wanted to be a `</section>` tag

Fix placement of excluded phenotypes in liricalHTML 

---

src/main/java/org/monarchinitiative/lirical/svg/Lirical2Svg.java
src/main/java/org/monarchinitiative/lirical/svg/Lr2Svg.java
src/main/java/org/monarchinitiative/lirical/svg/Posttest2Svg.java
src/main/java/org/monarchinitiative/lirical/svg/Sparkline2Svg.java

A few suggested changes to the color scheme. Generally I've changed things so that colors in sparkline graphs and graphs for each disease match, and so that supporting evidence is green and contradicting evidence is red. 
Specifically:
- changed all LRs supporting diagnosis to green, and all LRs contradicting diagnosis to red
(these previously were blue and red respectively)
- removed border around the rect for LRs of phenotypes but preserved border for genotypes, to provide a visual cue that these are different LRs
- changed color of diamond icon for excluded items that neither support nor contradict diagnosis to grey
- changed color of overall disease posterior probability to green (from orange)
Some screenshots with these changes highlighted below. @pnrobinson @jmcmurry What do you …

Coordinate and tweak colors for likelihood ratios

---

src/main/java/org/monarchinitiative/lirical/cmd/PhenopacketCommand.java
src/main/java/org/monarchinitiative/lirical/cmd/PrioritizeCommand.java
src/main/java/org/monarchinitiative/lirical/cmd/SimulatePhenopacketCommand.java
src/main/java/org/monarchinitiative/lirical/cmd/SimulatePhenotypeOnlyCommand.java
src/main/java/org/monarchinitiative/lirical/cmd/YamlCommand.java
src/main/java/org/monarchinitiative/lirical/configuration/LiricalFactory.java
src/main/java/org/monarchinitiative/lirical/io/YamlParser.java
src/main/java/org/monarchinitiative/lirical/output/HtmlTemplate.java

Added some non-elegant but straightforward code to check this. There is no way to enforce mutual exclusivity with JCommander apparently, and it would require a rewrite of LiricalFactory to do this in a really elegant way. We might consider using Spring to de-spaghettify the construction of objects in LIRICAL, and so I hope we can leave this for now.

adding checks that -m and -t cannot be used together and that -t \in [0,1]

---

src/main/java/org/monarchinitiative/lirical/configuration/LiricalFactory.java

Prevent outfilePrefix from being set to null in yaml mode when prefix is not specified in YAML file

Prevent outfilePrefix from being set to null

---

pom.xml
src/main/java/org/monarchinitiative/lirical/io/PhenopacketImporter.java

This is a curious thing. The build fails on my Mac without the dependency that is added in this PR. I am not sure, however, how come it does not fail on your side..

Add missing dependency `protobuf-java-util`.

---

src/main/java/org/monarchinitiative/lirical/cmd/AbstractPrioritizeCommand.java
src/main/java/org/monarchinitiative/lirical/cmd/PhenopacketCommand.java
src/main/java/org/monarchinitiative/lirical/cmd/SimulatePhenopacketWithVcfCommand.java
src/main/java/org/monarchinitiative/lirical/cmd/YamlCommand.java
src/main/java/org/monarchinitiative/lirical/io/YamlParser.java
src/test/java/org/monarchinitiative/lirical/io/YamlParserTest.java
src/test/resources/yaml/example2.yml

Add command line options to write TSV and HTML files in same analysis for YAML and PhenoPacket sub-command.
Write both files command examples for phenopacket 
```
LIRICAL.jar phenopacket ... --html true --tsv true
LIRICAL.jar phenopacket ... --tsv true
```
Write both files configuration example for YAML
```
analysis:
...
html: true
tsv: true
```

Writing of TSV and HTML in same run

---

lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/AbstractPrioritizeCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/AnalysisDataParserAwareCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/PhenopacketCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/PrioritizeCommand.java
lirical-configuration/src/main/java/org/monarchinitiative/lirical/configuration/LiricalBuilder.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/Lirical.java

`VariantParserFactory` is an optional attribute of `Lirical`. This allows running LIRICAL in absence of bulky Exomiser variant database.

`VariantParserFactory` is an optional attribute of `Lirical`.

---

lirical-benchmark/src/main/java/org/monarchinitiative/lirical/benchmark/cmd/BenchmarkCommand.java
lirical-beta/src/main/java/org/monarchinitiative/lirical/beta/cmd/AbstractPrioritizeCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/AbstractPrioritizeCommand.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/AnalysisOptions.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/AnalysisOptionsDefault.java

Add `PretestDiseaseProbability` to `AnalysisOptions` so that analyses can be run with different pretest disease probabilities. The `PretestDiseaseProbability` is deprecated in `LiricalBuilder`, scheduled for removal in `v2.0.0`.

Add `PretestDiseaseProbability` to `AnalysisOptions`.

---

pom.xml

Add a `dev` profile to use SNAPSHOT artifacts deployed to Sonatype snapshot repository.

Enable SNAPSHOTS in `dev` profile

---

lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/AbstractPrioritizeCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/BaseCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/BenchmarkCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/DownloadCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/LiricalConfigurationCommand.java
lirical-cli/src/main/resources/logback.xml

All logging is done on the console. By default, LIRICAL only reports warnings and errors. The verbosity can be increased using `-v`, `-vv` or `-vvv` CLI options to show *INFO*, *INFO + DEBUG*, or *INFO + DEBUG + TRACE* messages.

Rework logging

---

lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/LiricalConfigurationCommand.java
lirical-configuration/src/main/java/org/monarchinitiative/lirical/configuration/impl/BundledBackgroundVariantFrequencyServiceFactory.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/probability/PretestDiseaseProbabilities.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/GenotypeLikelihoodRatio.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/poisson/Gamma.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/poisson/MaxCountExceededException.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/poisson/NumberIsTooLargeException.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/poisson/NumberIsTooSmallException.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/poisson/PoissonDistribution.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/poisson/SaddlePointExpansion.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/ClinvarClnSig.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/VariantMetadata.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/service/BackgroundVariantFrequencyService.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/service/BackgroundVariantFrequencyServiceImpl.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/service/VariantMetadataService.java
lirical-exomiser-db-adapter/src/main/java/org/monarchinitiative/lirical/exomiser_db_adapter/ExomiserMvStoreMetadataService.java

- shrink API of the `core.likelihoodratio.poisson` package to the necessary minimum
- improve Javadoc, especially the important bits regarding variant frequencies
- use selected disease databases to calculate pretest disease probability

Shrink poisson API, improve javadocs, use selected disease databases to calculate pretest probability

---

.github/workflows/pages-latest.yml
.github/workflows/pages-stable.yml
pom.xml

- setup hosting of the docs on *github.io*, publish *latest* (`develop`) and *stable* (`master`) versions
- build aggregated Javadoc

Setup documentation on github.io

---

lirical-core/src/main/java/org/monarchinitiative/lirical/core/output/HtmlTemplate.java
lirical-core/src/main/resources/org/monarchinitiative/lirical/core/output/liricalHTML.ftl

Fixing `N/A` in HTML templates when run in phenotype-only mode

---

.gitignore
lirical-cli/src/examples/LDS2.yaml
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/AbstractPrioritizeCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/AnalysisDataParserAwareCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/LiricalConfigurationCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/YamlCommand.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/AnalysisDataParser.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/analysis/BaseAnalysisDataParser.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/analysis/PhenopacketAnalysisDataParser.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/analysis/YamlAnalysisDataParser.java

Fix bug in the code for genotype-aware analysis starting from a YAML file. The code did not take into account the selected genomic assembly and transcript database.

Fix code for genotype-aware analysis starting from a YAML file

---

lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/GenotypeLikelihoodRatio.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/GenotypeLrMatchType.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/GenotypeLrWithExplanation.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/ClinVarAlleleData.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/ClinvarClnSig.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/Gene2Genotype.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/LiricalVariantDefault.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/VariantMetadata.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/VariantMetadataDefault.java
lirical-core/src/test/java/org/monarchinitiative/lirical/core/likelihoodratio/GenotypeLikelihoodRatioTest.java
lirical-exomiser-db-adapter/src/main/java/org/monarchinitiative/lirical/exomiser_db_adapter/ExomiserMvStoreMetadataService.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/output/serialize/GenotypeLrWithExplanationSerializer.java
lirical-io/src/test/java/org/monarchinitiative/lirical/io/output/JsonAnalysisResultWriterTest.java

The PR adds more information to `GenotypeLrWithExplanation` to allow better explanation of genotype LRs downstream. 
The new enum `GenotypeLrMatchType` is conceptually similar to `LrMatchType` and describes the route of genotype LR calculation. Based on the enum value, the downstream code can determine how many causal variants need to be searched for and presented in the report.
@pnrobinson while working with the code, I also wanted to address #616 . Basically, we will ***NEVER*** include the variants with primary ClinVar interpretation from one of the following into consideration, when calculating the number of pathogenic alleles or pathogenicity bin score for a gene:
- BENIGN
- LIKELY_BENIGN
- BENIGN_OR_LIKELY_BENIGN
@pnrobinson can you please comment if this is what you wanted in #616, …

Enhance genotype LR matching

---

lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/Main.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/AbstractPrioritizeCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/LiricalConfigurationCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/OutputCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/PhenopacketCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/PhenopacketUtil.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/experimental/ExperimentalCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/experimental/PhenopacketsCommand.java
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/experimental/package-info.java

Add `experimental phenopackets` command for running LIRICAL in phenotype-only mode on a collection of phenopackets.

Add `experimental phenopackets` command

---

pom.xml

Configure `maven-source-plugin` to build source code during Maven install phase to improve ergonomics of using LIRICAL as a library, in particular for showing documentation and sources in IDEs.
The sources and javadocs are built in `release` profile only.

Build sources JAR during release

---

lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/AbstractPrioritizeCommand.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/output/HtmlTemplate.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/output/LiricalTemplate.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/output/TsvTemplate.java
lirical-io/src/main/resources/org/monarchinitiative/lirical/io/output/liricalHTML.ftl
lirical-io/src/main/resources/org/monarchinitiative/lirical/io/output/liricalTSV.ftl

Improve HTML and TSV outputs.
The HTML report now reports variant-related metadata only if the analysis was run with a VCF file.
The TSV report includes genes and variants only if run with a VCF file.
The HTML and TSV templates were simplified.
Fixes #609

Enhance output formats

---

lirical-core/src/main/java/org/monarchinitiative/lirical/core/LiricalOptions.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/AnalysisData.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/AnalysisDataDefault.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/AnalysisDataParser.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/LiricalParseException.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/impl/package-info.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/package-info.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/probability/package-info.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/exception/LiricalAnalysisException.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/exception/package-info.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/io/package-info.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/package-info.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/Age.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/HpoCase.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/model/package-info.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/package-info.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/service/package-info.java
lirical-core/src/test/java/org/monarchinitiative/lirical/core/model/HpoCaseTest.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/package-info.java

Previously we could have `Age` that was unknown. However, this is better modeled by making the `Age` optional and using `null` to represent its absence, since `null` conveys the same meaning.
The PR simplifies the code that uses `Age` and adds bounds checks on values to prevent using negative years, months, ... .

Simplify handling of subject's age

---

lirical-configuration/pom.xml

`logback-classic` should not have never been in `lirical-configuration` 😱

Remove misplaced dependency from `lirical-configuration` POM

---

docs/running.rst
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/OutputCommand.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/GenotypeLrMatchType.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/output/OutputOptions.java
lirical-core/src/test/java/org/monarchinitiative/lirical/core/likelihoodratio/GenotypeLrMatchTypeTest.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/output/HtmlTemplate.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/output/LiricalTemplate.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/output/SparklinePacket.java
lirical-io/src/main/java/org/monarchinitiative/lirical/io/output/TsvTemplate.java
lirical-io/src/test/java/org/monarchinitiative/lirical/io/output/JsonAnalysisResultWriterTest.java

The PR updates the HTML and TSV report generators, to ensure we only report the candidate diseases with predicted pathogenic variant(s) in the associated gene.
This filtering is on by default, and can be turned off by including the `--sdwndv` flag in the CLI.

Do not show the candidate disease unless there is a (predicted) pathogenic variant(s) in the associated gene

---

lirical-io/src/main/resources/org/monarchinitiative/lirical/io/output/liricalTSV.ftl

Remove the extra `\t` from the TSV template.
Fixes #656

Remove extra `\t` from the TSV template

---

docs/running.rst
lirical-cli/src/main/java/org/monarchinitiative/lirical/cli/cmd/LiricalConfigurationCommand.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/AnalysisOptions.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/AnalysisOptionsDefault.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/analysis/impl/LiricalAnalysisRunnerImpl.java
lirical-core/src/main/java/org/monarchinitiative/lirical/core/likelihoodratio/PhenotypeLikelihoodRatio.java

Allow scoping the analysis on a subset of diseases with the `--target-diseases` option (CLI) or `AnalysisOptions.Builder.setTargetDiseases` (API).

Allow focusing the prioritization on a subset of diseases
